name: Ping Web Site

on:
  workflow_dispatch:
  # push:
    # branches: [ master ]
  # schedule: 
    # - cron: '*/10 * * * *' #every 10 minutes
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: Ping www.google.com
      run: Web.Ping --host https://www.google.com
    - name: Ping www.cdnblackmyth.vip
      run: Web.Ping --host https://www.cdnblackmyth.vip
